### ISSUE TITLE
Getting an error "ImportError: cannot import name '_batch_mat_mul'"

### ISSUE THREAD

**Issue by mady143** [tblee/QA_RandomCoattentionForest#1]
Hi @tblee ,

I am using your code and when I am trying to execute the train.py from code folder getting an error **"ImportError: cannot import name '_batch_mat_mul'"** could t=you help me resolve this issue

Thanks & Regards,
Manikantha Sekhar.

Happy Codding..

**Comment by mmusunur** [comment]
Hi,
Just downgrade the tensorflow version to 0.12.1 this will help you to resolve this issue..

Thanks & Regards,
Manikantha Sekhar...
